#Configuracion
#Thu May 14 21:53:09 MST 2026
registration.image.last.directory=C\:\\Users\\DASC\\Desktop
registration.window.height=655
registration.window.width=1192
registration.window.x=376
registration.window.y=390
ui.theme=dark
users.export.pdf=C\:\\Users\\azari\\OneDrive\\Desktop\\Base de Datos
uz\#Configuracion=
