#Configuracion
#Wed May 06 09:37:24 MST 2026
registration.image.last.directory=C\:\\Users\\DASC\\Desktop
registration.window.height=614
registration.window.width=1032
registration.window.x=204
registration.window.y=94
ui.theme=dark
users.export.pdf=C\:\\Users\\josec\\Downloads
