#Configuracion
#Sun May 10 10:25:02 MST 2026
registration.image.last.directory=C\:\\Users\\DASC\\Desktop
registration.window.height=614
registration.window.width=1032
registration.window.x=341
registration.window.y=263
ui.theme=dark
users.export.pdf=C\:\\Users\\josec\\OneDrive\\Documentos\\Escuela
